name: Test wheels

on:
  workflow_dispatch:
    inputs:
      run-id:
        description: 'Workflow run id'
        required: true

jobs:

  tox:
    if: (success() || failure())
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - sagemath-bliss
          - sagemath-categories
          - sagemath-combinat
          - sagemath-coxeter3
          - sagemath-flint
          - sagemath-giac
          - sagemath-graphs
          - sagemath-groups
          - sagemath-modules
          - sagemath-pari
          - sagemath-plot
          - sagemath-polyhedra
          - sagemath-repl
          - sagemath-schemes
          - sagemath-singular
          - sagemath-standard-no-symbolics
          - sagemath-symbolics
        os:
          - ubuntu-latest
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: "${{ matrix.os }}-*-wheels"
          path: wheelhouse
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run-id }}
      - uses: actions/download-artifact@v4
        with:
          pattern: "noarch-wheels"
          path: wheelhouse
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run-id }}
      - uses: actions/download-artifact@v4
        with:
          pattern: "dist"
          path: wheelhouse
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run-id }}
      - uses: actions/setup-python@v5
        id: python
        with:
          python-version: "3.10"
      - name: Install tox
        run: |
          pip install tox
      - name: Run tox
        run: |
          set -x
          pkg=${{ matrix.distribution }}
          WHEELHOUSE=$(pwd)/wheelhouse
          export PIP_FIND_LINKS=file://$WHEELHOUSE
          cd pkgs/$pkg
          pkg_underscore=${pkg//-/_}
          case "${{ matrix.os }}" in
              ubuntu*)  tag="manylinux*_x86_64";;
              macos-13) tag="macosx_*_x86_64";;
              macos-14) tag="macosx_*_arm64";;
          esac
          wheel_pattern="$WHEELHOUSE/*$pkg_underscore*-cp310-$tag.whl"
          eval ls -l $wheel_pattern
          wheel=$(eval ls $wheel_pattern | head -n1)
          if [ -n "$wheel" ]; then
              eval tox -v -v -e py310-norequirements --installpkg "$wheel"
          fi
      - name: Update known test failures
        if: (success() || failure())
        run: |
          export SAGE_ROOT=$(pwd)
          WHEELHOUSE=$(pwd)/wheelhouse
          export PIP_FIND_LINKS=file://$WHEELHOUSE
          ./bootstrap sagemath_environment sagemath_repl
          pip install pkgs/sagemath-environment pkgs/passagemath-repl
          pkg=${{ matrix.distribution }}
          cd pkgs/$pkg
          sage --fixdoctests --distribution "$pkg" --venv .tox/py310-norequirements --update-known-test-failures
          git diff
