name: Test wheels

on:
  workflow_dispatch:
    inputs:
      run-id:
        description: 'Workflow run id'
        required: true
  workflow_call:
    inputs:
      run-id:
        type: string
        required: true

jobs:

  tox:
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - sagemath-benzene
          - sagemath-bliss
          - sagemath-buckygen
          - sagemath-categories
          - sagemath-cddlib
          - sagemath-cliquer
          - sagemath-cmr
          - sagemath-combinat
          - sagemath-coxeter3
          - sagemath-ecl
          - sagemath-eclib
          - sagemath-flint
          - sagemath-gap
          - sagemath-giac
          - sagemath-glucose
          - sagemath-graphs
          - sagemath-groups
          - sagemath-homfly
          - sagemath-kissat
          - sagemath-latte-4ti2
          - sagemath-libbraiding
          - sagemath-linbox
          - sagemath-lrslib
          - sagemath-maxima
          - sagemath-modules
          - sagemath-msolve
          - sagemath-ntl
          - sagemath-palp
          - sagemath-pari
          - sagemath-planarity
          - sagemath-plantri
          - sagemath-plot
          - sagemath-polyhedra
          - sagemath-qepcad
          - sagemath-rankwidth
          - sagemath-rubiks
          - sagemath-schemes
          - sagemath-sirocco
          - sagemath-singular
          - sagemath-standard-no-symbolics
          - sagemath-symbolics
        os:
          - ubuntu-latest
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: "${{ matrix.os }}-*-wheels"
          path: wheelhouse
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run-id || inputs.run-id }}
      - uses: actions/download-artifact@v4
        with:
          pattern: "noarch-wheels"
          path: wheelhouse
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run-id || inputs.run-id }}
      - uses: actions/download-artifact@v4
        with:
          pattern: "dist"
          path: wheelhouse
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run-id || inputs.run-id }}
      - uses: actions/setup-python@v5
        id: python
        with:
          python-version: "3.10"
      - name: Install tox
        run: |
          pip install tox
      - name: Run tox
        run: |
          set -x
          pkg=${{ matrix.distribution }}
          pkg_underscore=${pkg//-/_}
          WHEELHOUSE=$(pwd)/wheelhouse
          export PIP_FIND_LINKS=file://$WHEELHOUSE
          (set +x; cd "$WHEELHOUSE" && for whl in *.whl; do
               case $whl in
                   *$pkg_underscore-*)     ;;
                   *musllinux*)            ;;
                   *_i686*)                ;;
                   *-cp310-*|*-none-any-*) echo "${whl%%-*} @ file://$WHEELHOUSE/$whl";;
               esac;
           done) | tee constraints.txt
          export PIP_CONSTRAINT=$(pwd)/constraints.txt
          case "${{ matrix.os }}" in
              ubuntu*)  tag="manylinux*_x86_64";;
              macos-13) tag="macosx_*_x86_64";;
              macos-14) tag="macosx_*_arm64";;
          esac
          wheel_pattern="$WHEELHOUSE/*$pkg_underscore*-cp310-$tag.whl"
          eval ls -l $wheel_pattern
          wheel=$(eval ls $wheel_pattern | head -n1)
          if [ -n "$wheel" ]; then
              cd pkgs/$pkg
              tox_envs=$(tox -l -q| sed 's/sagepython-.*nopypi-norequirements/py310-norequirements/')
              eval tox -v -v -e $(for env in $tox_envs; do echo -n "$comma$env"; comma=,; done) --installpkg "$wheel"
          fi
      - name: Update known test failures
        if: (success() || failure())
        run: |
          set -x
          export SAGE_ROOT=$(pwd)
          WHEELHOUSE=$(pwd)/wheelhouse
          export PIP_FIND_LINKS=file://$WHEELHOUSE
          ./bootstrap sagemath_environment sagemath_repl
          pip install pkgs/sagemath-environment pkgs/sagemath-repl
          pkg=${{ matrix.distribution }}
          cd pkgs/$pkg
          extras=$(tox -l -q| sed -E 's/sagepython-.*nopypi-norequirements//;s/^-(.*)/[\1]/;s/-/,/;s/^/'$pkg'/;')
          for extra in $extras; do
              sage --fixdoctests --distribution "$extra" --toxenv py310-norequirements --update-known-test-failures || echo "(ignored)"
          done
          git diff
